/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2203 from the
 * contents of XS.xs. Do not edit this file, edit XS.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "XS.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"
#include "petrovich.h"

#define MY_CXT_KEY "MR::Petrovich::XS::_guts" XS_VERSION

typedef struct {
    petr_context_t* petr_ctx;
} my_cxt_t;

START_MY_CXT;

SV * _inflect(const char *data, size_t len, petr_name_kind_t kind, petr_gender_t gender, petr_case_t dest_case) {
    dMY_CXT;

    size_t dest_buf_size = len*4;
    SV *ret = newSV(dest_buf_size);
    SvPOK_on(ret);

    size_t dest_len;
    char *dest = SvPVutf8_nolen(ret);

    int code = petr_inflect(MY_CXT.petr_ctx,data,len,kind,gender,dest_case,dest,dest_buf_size,&dest_len); 
    if(code != 0) { 
        SvREFCNT_dec(ret);
        return &PL_sv_undef;
    }
    
    SvCUR_set(ret, dest_len);
    return ret;
}

#line 46 "XS.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 98 "XS.c"

XS(XS_MR__Petrovich__XS_init_from_file); /* prototype to pass -Wmissing-prototypes */
XS(XS_MR__Petrovich__XS_init_from_file)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "path");
    {
	const char *	path = (const char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;
#line 48 "XS.xs"
    dMY_CXT;
    RETVAL = petr_init_from_file(path, &MY_CXT.petr_ctx);
#line 117 "XS.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_MR__Petrovich__XS_free_context); /* prototype to pass -Wmissing-prototypes */
XS(XS_MR__Petrovich__XS_free_context)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 56 "XS.xs"
    dMY_CXT;
    petr_free_context(MY_CXT.petr_ctx);
#line 138 "XS.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_MR__Petrovich__XS__inflect_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_MR__Petrovich__XS__inflect_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "data, len, kind, gender, dest_case");
    {
	const char *	data = (const char *)SvPV_nolen(ST(0));
	size_t	len = (size_t)SvUV(ST(1));
	petr_name_kind_t	kind = (petr_name_kind_t)SvIV(ST(2));
	petr_gender_t	gender = (petr_gender_t)SvIV(ST(3));
	petr_case_t	dest_case = (petr_case_t)SvIV(ST(4));
	SV *	RETVAL;
#line 67 "XS.xs"
    RETVAL = _inflect(data,len,kind,gender,dest_case);
#line 163 "XS.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_MR__Petrovich__XS__inflect_first_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_MR__Petrovich__XS__inflect_first_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "data, len, gender, dest_case");
    {
	const char *	data = (const char *)SvPV_nolen(ST(0));
	size_t	len = (size_t)SvUV(ST(1));
	petr_gender_t	gender = (petr_gender_t)SvIV(ST(2));
	petr_case_t	dest_case = (petr_case_t)SvIV(ST(3));
	SV *	RETVAL;
#line 78 "XS.xs"
    RETVAL = _inflect(data,len,NAME_FIRST,gender,dest_case);
#line 189 "XS.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_MR__Petrovich__XS__inflect_middle_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_MR__Petrovich__XS__inflect_middle_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "data, len, gender, dest_case");
    {
	const char *	data = (const char *)SvPV_nolen(ST(0));
	size_t	len = (size_t)SvUV(ST(1));
	petr_gender_t	gender = (petr_gender_t)SvIV(ST(2));
	petr_case_t	dest_case = (petr_case_t)SvIV(ST(3));
	SV *	RETVAL;
#line 89 "XS.xs"
    RETVAL = _inflect(data,len,NAME_MIDDLE,gender,dest_case);
#line 215 "XS.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_MR__Petrovich__XS__inflect_last_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_MR__Petrovich__XS__inflect_last_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "data, len, gender, dest_case");
    {
	const char *	data = (const char *)SvPV_nolen(ST(0));
	size_t	len = (size_t)SvUV(ST(1));
	petr_gender_t	gender = (petr_gender_t)SvIV(ST(2));
	petr_case_t	dest_case = (petr_case_t)SvIV(ST(3));
	SV *	RETVAL;
#line 100 "XS.xs"
    RETVAL = _inflect(data,len,NAME_LAST,gender,dest_case);
#line 241 "XS.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_MR__Petrovich__XS); /* prototype to pass -Wmissing-prototypes */
XS(boot_MR__Petrovich__XS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("MR::Petrovich::XS::init_from_file", XS_MR__Petrovich__XS_init_from_file, file);
        newXS("MR::Petrovich::XS::free_context", XS_MR__Petrovich__XS_free_context, file);
        newXS("MR::Petrovich::XS::_inflect_name", XS_MR__Petrovich__XS__inflect_name, file);
        newXS("MR::Petrovich::XS::_inflect_first_name", XS_MR__Petrovich__XS__inflect_first_name, file);
        newXS("MR::Petrovich::XS::_inflect_middle_name", XS_MR__Petrovich__XS__inflect_middle_name, file);
        newXS("MR::Petrovich::XS::_inflect_last_name", XS_MR__Petrovich__XS__inflect_last_name, file);

    /* Initialisation Section */

#line 39 "XS.xs"
{
    MY_CXT_INIT;
    MY_CXT.petr_ctx = NULL;
}

#line 284 "XS.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

